<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSkGxaXM\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSkGxaXM/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSkGxaXM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSkGxaXM\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSkGxaXM\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SkGxaXM',
    'container.build_id' => '8fafc175',
    'container.build_time' => 1551884348,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSkGxaXM');
