<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQWewx1L\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQWewx1L/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQWewx1L.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQWewx1L\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQWewx1L\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'QWewx1L',
    'container.build_id' => 'f65f21fe',
    'container.build_time' => 1551700562,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQWewx1L');
